### ISSUE TITLE
Build Error ( inventory.ts(102,76) )

### ISSUE THREAD

**Issue by ExplosionMagicMegumin** [L-Leite/cso2-users-service#9]
[root@localhost users-service]# gulp build
[23:39:06] Using gulpfile /home/nodejs/server/users-service/gulpfile.js
[23:39:06] Starting 'build'...
[23:39:06] Starting 'clean:dist'...
[23:39:06] Cleaning transpiled source...
[23:39:06] Finished 'clean:dist' after 17 ms
[23:39:06] Starting 'tslint'...
[23:39:06] Linting source code...
[23:39:08] Finished 'tslint' after 1.39 s
[23:39:08] Starting 'typescript'...
[23:39:08] Transpiling source code...
src/entities/inventory/inventory.ts(102,76): error TS2322: Type 'number' is not assignable to type 'Partial<InventoryItem> | { itemId?: QuerySelector<number>; ammount?: QuerySelector<number>; }'.
TypeScript: 1 semantic error
TypeScript: emit succeeded (with errors)
[23:39:19] 'typescript' errored after 11 s
[23:39:19] Error: TypeScript: Compilation failed
    at Output.mightFinish (/home/nodejs/server/users-service/node_modules/gulp-typescript/release/output.js:130:43)
    at applySourceMap.then.appliedSourceMap (/home/nodejs/server/users-service/node_modules/gulp-typescript/release/output.js:43:22)
[23:39:19] 'build' errored after 12 s
[root@localhost users-service]#

**Comment by ExplosionMagicMegumin** [comment]
@dounai2333  @L-Leite help please!

**Comment by ExplosionMagicMegumin** [comment]
fix!
